[package]
name = "time-demo"
version = "0.1.0"
edition = "2021"

default-run = "time-demo"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.35"
