[package]
name = "rand-demo"
version = "0.1.0"
edition = "2021"

default-run = "rand-demo"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
