[package]
name = "url-dispatch"
version = "0.1.0"
edition = "2021"

default-run = "url-dispatch"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
