[package]
name = "tracing-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.28"
color-eyre = "0.6.2"
log = "0.4.21"
serde_json = "1.0.114"
tokio = {"version" = "1.36.0", features = ["full"]}
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-core = "0.1.32"
tracing-error = "0.2.0"
tracing-subscriber = "0.3.17"
