[workspace]
# A separate workspace

[package]
name = "sea-query-diesel-mysql-example"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }
time = { version = "0.3", features = ["parsing", "macros"] }
serde_json = { version = "1" }
uuid = { version = "1", features = ["serde", "v4"] }
diesel = { version = "2.1.1", features = ["mysql"] }
sea-query = "0.30.7"
sea-query-diesel = { version = "0.1.0", features = [
    "mysql",
    "with-chrono",
    "with-json",
    "with-uuid",
    "with-time",
] }

#sea-query = { path = "../.." }
#sea-query-diesel = { path = "../../sea-query-diesel", features = [
#  "mysql",
#  "with-chrono",
#  "with-json",
#  "with-uuid",
#  "with-time",
#] }

# NOTE: if you are copying this example into your own project, use the following line instead:
# sea-query = { version = "0"}
# sea-query-diesel = { version = "0", features = [...] }
